### ISSUE TITLE
Attachments not working

### ISSUE THREAD

**Issue by paaland** [rfinochi/pop3dotnet#19]
I'm trying to use this library to fetch POP3 email via SSL from Office 365. Messages works fine, but message.Attachments is always empty even though I cen see via Outlook that the messages has Excel attachments.

**Comment by rfinochi** [comment]
Hi,

Sorry but currently the library not support automatic attach parsing.

You can access the complete message using the RawMessage property and manually parse the MINE attach.

Regards
