### ISSUE TITLE
Large attachments do not download properly.

### ISSUE THREAD

**Issue by HLalumiere** [rfinochi/pop3dotnet#21]
Everything about this component is great, but I have a single problem with large-ish attachment. Trying to download a message from a POP3 server with a 4MB .txt file attachment results in a hang. From what I could see it looks like the component is downloading the file but at something like 10KB/s. I have tried other components, as well as multiple email clients, and they all work fine, so this is not a server issue. Unfortunately these other components have other drawbacks that make me want to wait for a fix on yours. Thanks!

**Comment by HLalumiere** [comment]
So, after a tiny bit of profiling, I found the issue and corrected it locally... Not really sure how to use github to propose patches, but here is the gist of it:

In Pop3Client.cs, there are a few instances of straight string concatenations using the += operator. This is notoriously slow when strings are long. For example:

`public void RetrieveHeader( Pop3Message message )
{
	if ( !this.IsConnected )
		throw new InvalidOperationException( "Pop3 client is not connected to host" );

	if ( message == null )
		throw new ArgumentNullException( "message" );

	SendCommand( "TOP", "0", message );

	while ( true )
	{
		string response = _networkOperations.Read( );
		if ( response == ".\r\n" )
			break;

		message.RawHeader += response;
	}
}`

should instead use a StringBuilder and become:

`public void RetrieveHeader( Pop3Message message )
{
	if ( !this.IsConnected )
		throw new InvalidOperationException( "Pop3 client is not connected to host" );

	if ( message == null )
		throw new ArgumentNullException( "message" );

	SendCommand( "TOP", "0", message );

	var sbRawMsg = new StringBuilder();

	while ( true )
	{
		string response = _networkOperations.Read( );
		if ( response == ".\r\n" )
			break;

		sbRawMsg.Append(response);
	}

	message.RawHeader = sbRawMsg.ToString();
}`

The same problem exists in the following methods:

RetrieveHeader(Pop3Message message)
Retrieve(Pop3Message message)
RetrieveHeaderAsync(Pop3Message message)
RetrieveAsync(Pop3Message message)

For now my issue is solved, but this should really be an easy commit.

Thanks!

**Comment by rfinochi** [comment]
Hi!

Sorry for the delay in the anwser.

Thks so much for the fix. I update the code, run the tests, and publish a new version with this patch.

Thks again!

**Comment by HLalumiere** [comment]
No problem friend, happy to be of help!

Cheers!

**Comment by rfinochi** [comment]
Hi!

I merge the changes and publish a new version in Nuget (2.2.0)



Thks
