### ISSUE TITLE
How to read content from attachments

### ISSUE THREAD

**Issue by CodeLearner21** [rfinochi/pop3dotnet#22]
I am not able to read content from attachment. when I checked in debug mode all attachment content showing in message.Body only.

Thanks

**Comment by rfinochi** [comment]
Hi,

You need to use the RawMessage property of the Message object, and parse
the Nine Attachement.

Regards!

**Comment by srinivaspillalamarri** [comment]
Try to provide the filter option if possible.

Working nice but when my data is high then I want to filter it out.
That option is missing.

**Comment by rfinochi** [comment]
Hi,

The pop3 protocol don't have filtering. You need download all mails and then filter by yourself
