### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by ByronAP** [rfinochi/pop3dotnet#23]
Where is the source? or is this a library to sucker people that do not know better?

**Comment by rfinochi** [comment]
Hi

The source is in the master branch (as usual)

https://github.com/rfinochi/pop3dotnet/tree/master

**Comment by ByronAP** [comment]
haaahaaahaaaaa oh man my bad, I did not even think to look at the branch.. sorry man and keep up the good work

**Comment by rfinochi** [comment]
Thks and don't worry.
