### ISSUE TITLE
Error Retrieve Mail

### ISSUE THREAD

**Issue by matteozoni** [rfinochi/pop3dotnet#24]
Hi, I have an error trying to retrieve some emails.

I translate the error message from Italian

The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)

Buffer dei caratteri di output troppo piccolo per contenere i caratteri decodificati. Codifica 'Unicode (UTF-8)', fallback 'System.Text.DecoderReplacementFallback'.

How can I recover other useful information for debugging?

Thanks

**Comment by rfinochi** [comment]
Hi,

You could send me (or attach in a reply of this message) a copy of some of the mails that will generate the problem?

**Comment by matteozoni** [comment]
Hi thanks for the reply.

I will privately send you the message number 21 (message.Number = 21) which generates the error.


In the catch of the error I put the POP3 Disconnect command and an error is generated that includes a piece of the mail number 20 (message.Number = 20).

```
                catch (Exception e)
                {
                    NErrore++;

                    pop3Client.Disconnect();
                    pop3Client.Dispose();
                    return;
                }
```


I'll even have that mail.

Here the detail of the error during the disconnection

```
Errore server nell'applicazione '/'.
assente fino al giorno 10/12/2018
Descrizione: Eccezione non gestita durante l'esecuzione della richiesta Web corrente. Per ulteriori informazioni sull'errore e sul suo punto di origine nel codice, vedere la traccia dello stack. 

Dettagli eccezione: System.InvalidOperationException: assente fino al giorno 10/12/2018


Errore nel codice sorgente: 


Riga 286:                    //StrMail += "ERRORE: " + "MessageId: " + message.MessageId + ", " + "Date: " + message.Date + ", " + "From: " + message.From + ", " + "To: " + message.To + ", " + "Subject: " + message.Subject + "<br />";
Riga 287:
Riga 288:                    pop3Client.Disconnect();
Riga 289:                    pop3Client.Dispose();
Riga 290:                    return;

File di origine: C:\Users\Matteo Zoni\Documents\Visual Studio 2017\Projects\123\123\admin\fg2-newsletters-invio.aspx.cs    Riga: 288 

Traccia dello stack: 


[InvalidOperationException: assente fino al giorno 10/12/2018
]
   Pop3.Pop3Client.SendCommand(String command, String aditionalParameters, Pop3Message message) +437
   Pop3.Pop3Client.Disconnect() +53
   euromask_shop.com.admin.fg2_newsletters_invio.CheckBadMail() in C:\Users\Matteo Zoni\Documents\Visual Studio 2017\Projects\123\123\admin\fg2-newsletters-invio.aspx.cs:288
   euromask_shop.com.admin.fg2_newsletters_invio.Page_Load(Object sender, EventArgs e) in C:\Users\Matteo Zoni\Documents\Visual Studio 2017\Projects\123\123\admin\fg2-newsletters-invio.aspx.cs:19
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.Web.UI.Control.OnLoad(EventArgs e) +95
   System.Web.UI.Control.LoadRecursive() +59
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +678

Informazioni di versione: Versione di Microsoft .NET Framework:4.0.30319; Versione di ASP.NET:4.7.3282.0
```

**Comment by rfinochi** [comment]
Hi Matteo,

I try to reproduce the error with the mails that you sent to me, but I not get any exception.

You can try to debug the error directly with the code of the pop3 library?

**Comment by matteozoni** [comment]
Hi thanks for the reply, I will send you the credentials to access the mailbox and the source code that generates the error (when retrieve the mail number 21).

Thanks

**Comment by rfinochi** [comment]
Hi Matteo,

I found the bug!

I fix it, and publish a new nuget package (https://www.nuget.org/packages/Pop3/2.2.2) and push the fix in github report (https://github.com/rfinochi/pop3dotnet/tree/master).

Thks for reporting the bug!
