### ISSUE TITLE
DeleteAsync is wrong.

### ISSUE THREAD

**Issue by senioi** [rfinochi/pop3dotnet#25]
pop3Client.DeleteAsync(message)

>     public async Task DeleteAsync( Pop3Message message )
>         {
>             if ( !this.IsConnected )
>                 throw new InvalidOperationException( "Pop3 client is not connected to host" );
> 
>             if ( message == null )
>                 throw new ArgumentNullException( "message" );
> 
>             await SendCommandAsync( "DELE", message ).ConfigureAwait( false );
>         }

we need Number not is all i think

**Comment by senioi** [comment]
Sorry about this report.
Code not wrong for here.
But can't delete email for pop3 server.
Use telnet enter DELE 1  is work.

**Comment by rfinochi** [comment]
Hi,

Try with another server.

**Comment by SciChartTeam** [comment]
I had this problem too.  Turns out Delete only marks a message as deleted.  It isn't actually deleted until you send a QUIT command, which here means calling Disconnect.  Disconnect is NOT called on Dispose, which it really should be.

**Comment by rfinochi** [comment]
Thks for the researchon this issue.

I fix the bug and pust the coda and the package in nuget.

Thks!
