### ISSUE TITLE
pop3Client.ListAndRetrieveAsync - Attachments not populated

### ISSUE THREAD

**Issue by NemoKradXNA** [rfinochi/pop3dotnet#27]
When calling this method, it returns the emails in the in box, but the attachments are not populated, I can see them in the Pop3Message.Body, but they are not populated in Pop3Message.Attachements, it's always empty.

Am I missing another call that is needed to populate the Attachements?

Thanks in advance.

**Comment by rfinochi** [comment]
Hi,

Sorry but currently the library not support automatic attach parsing.

You can access the complete message using the RawMessage property and manually parse the MINE attach.

Regards

**Comment by NemoKradXNA** [comment]
Ah, that is a shame, any idea when that will be implemented?

**Comment by rfinochi** [comment]
Sorry, but I currently don't have an estimated ETA to implement this feature.
